global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "auth-microservice"
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    http_headers:
      x-api-key:
        files:
          - /etc/prometheus/secrets/x-api-key
    static_configs:
      - targets: ["host.docker.internal:3005"]
        labels:
          service: "auth-microservice"
          environment: "local"
