import { HttpStatus } from '@nestjs/common';
import { BaseServiceException } from 'src/common/exceptions/base-service.exception';

export enum UsersErrorCodes {
  SESSION_INVALID = 'SESSION_INVALID',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
  USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED',
  USER_PERSON_ALREADY_REGISTERED = 'USER_PERSON_ALREADY_REGISTERED',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_NOT_INITIALIZED = 'USER_NOT_INITIALIZED',
  TOKENS_ISSUE_ERROR = 'TOKENS_ISSUE_ERROR',
  RESET_PASSWORD_INVALID = 'RESET_PASSWORD_INVALID',
  RESET_PASSWORD_USER_NOT_FOUND = 'RESET_PASSWORD_USER_NOT_FOUND',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
}

export class UsersException extends BaseServiceException {
  constructor(message: string, errorCode: UsersErrorCodes, status: HttpStatus, cause?: Error) {
    super(message, errorCode, status, cause);
  }
}
