# Nombre del workflow
name: Run Jest tests

# Se ejecuta en cada push o pull request a la rama 'main'
on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # La máquina virtual donde correrá el trabajo
    runs-on: ubuntu-latest

    steps:
      #1. Configura Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 2. Clona tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3. Configura Node.js v24.5.0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.5.0'
          cache: 'npm'

      # 4. Instala las dependencias
      - name: Install dependencies
        run: npm ci

      # 5. Ejecuta todas las pruebas (unitarias y de integración)
      - name: Run tests
        run: npm run test
