import { HttpStatus } from '@nestjs/common';
import { BaseServiceException } from 'src/common/exceptions/base-service.exception';

export enum EndpointPermissionRulesErrorCodes {
  ENDPOINT_PERMISSION_RULE_NOT_CREATED = 'ENDPOINT_PERMISSION_RULE_NOT_CREATED',
  ENDPOINT_PERMISSION_RULE_NOT_UPDATED = 'ENDPOINT_PERMISSION_RULE_NOT_UPDATED',
  ENDPOINT_PERMISSION_RULE_NOT_DELETED = 'ENDPOINT_PERMISSION_RULE_NOT_DELETED',
  ENDPOINT_PERMISSION_RULE_ASSIGN_FAILED = 'ENDPOINT_PERMISSION_RULE_ASSIGN_FAILED',
  ENDPOINT_PERMISSION_RULE_ALREADY_EXISTS = 'ENDPOINT_PERMISSION_RULE_ALREADY_EXISTS',
  ENDPOINT_PERMISSION_RULE_ALREADY_ENABLED = 'ENDPOINT_PERMISSION_RULE_ALREADY_ENABLED',
  ENDPOINT_PERMISSION_RULE_ALREADY_DISABLED = 'ENDPOINT_PERMISSION_RULE_ALREADY_DISABLED',
  ENDPOINT_PERMISSION_RULE_NOT_FOUND = 'ENDPOINT_PERMISSION_RULE_NOT_FOUND',
}

export class EndpointPRException extends BaseServiceException {
  constructor(message: string, errorCode: EndpointPermissionRulesErrorCodes, status: HttpStatus, cause?: Error) {
    super(message, errorCode, status, cause);
  }
}
