import { HttpException, HttpStatus } from '@nestjs/common';

export enum EndpointPermissionRulesErrorCodes {
  ENDPOINT_PERMISSION_RULE_NOT_CREATED = 'ENDPOINT_PERMISSION_RULE_NOT_CREATED',
  ENDPOINT_PERMISSION_RULE_NOT_UPDATED = 'ENDPOINT_PERMISSION_RULE_NOT_UPDATED',
  ENDPOINT_PERMISSION_RULE_NOT_DELETED = 'ENDPOINT_PERMISSION_RULE_NOT_DELETED',
  ENDPOINT_PERMISSION_RULE_ASSIGN_FAILED = 'ENDPOINT_PERMISSION_RULE_ASSIGN_FAILED',
  ENDPOINT_PERMISSION_RULE_ALREADY_EXISTS = 'ENDPOINT_PERMISSION_RULE_ALREADY_EXISTS',
  ENDPOINT_PERMISSION_RULE_ALREADY_ENABLED = 'ENDPOINT_PERMISSION_RULE_ALREADY_ENABLED',
  ENDPOINT_PERMISSION_RULE_ALREADY_DISABLED = 'ENDPOINT_PERMISSION_RULE_ALREADY_DISABLED',
  ENDPOINT_PERMISSION_RULE_NOT_FOUND = 'ENDPOINT_PERMISSION_RULE_NOT_FOUND',
}

export class EndpointPRException extends HttpException {
  constructor(message: string, errorCode: EndpointPermissionRulesErrorCodes, status: HttpStatus) {
    super(
      {
        message,
        errorCode,
        statusCode: status,
      },
      status,
    );
  }
}
